export const BOOKS_LIST_REQUEST = 'BOOKS_LIST_REQUEST'
export const BOOKS_LIST_SUCCESS = 'BOOKS_LIST_SUCCESS'
export const BOOKS_LIST_FAIL = 'BOOKS_LIST_FAIL'

export const BOOK_DETAIL_REQUEST = 'BOOK_DETAIL_REQUEST'
export const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS'
export const BOOK_DETAIL_FAIL = 'BOOK_DETAIL_FAIL'


export const BOOKS_CREATE_REQUEST = 'BOOKS_CREATE_REQUEST'
export const BOOKS_CREATE_SUCCESS = 'BOOKS_CREATE_SUCCESS'
export const BOOKS_CREATE_FAIL = 'BOOKS_CREATE_FAIL'
export const BOOKS_CREATE_RESET = 'BOOKS_CREATE_RESET'

export const BOOKS_EDIT_REQUEST = 'BOOKS_EDIT_REQUEST'
export const BOOKS_EDIT_SUCCESS = 'BOOKS_EDIT_SUCCESS'
export const BOOKS_EDIT_FAIL = 'BOOKS_EDIT_FAIL'
export const BOOKS_EDIT_RESET = 'BOOKS_EDIT_RESET'

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST'
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS'
export const BOOK_DELETE_RESET = 'BOOK_DELETE_RESET'

export const BOOKS_MATCH_REQUEST = "BOOKS_MATCH_REQUEST";
export const BOOKS_MATCH_SUCCESS = "BOOKS_MATCH_SUCCESS";