# Generated by Django 4.0.6 on 2022-10-21 17:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='placeholder.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='')),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
